config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects, only: [:create, :show, :edit, :update] do
    resources :records, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :records
    
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :project
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :projects
  has_many :records
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @projects = Project.all
    @project = Project.new
  end
  
  def create
    current_user.projects.create(project_params)
    redirect_to root_path
  end
  
  def show
    @project = Project.find_by(id: params[:id])
    if !@project.present?
      redirect_to root_path
    else
      @summary = Record.where(:project_id => @project).sum(:duration_of_work)
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)
    redirect_to root_path
  end
  
  private
  
  def project_params
    params.require(:project).permit(:name, :description, :project_id) 
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @project = Project.find(params[:project_id])
    @record = Record.new
  end
  
  def create
    @project = Project.find(params[:project_id])
    @records = @project.records.create(record_params)
    redirect_to project_path(@project)
  end


  private
  
  def project_params
    params.require(:project).permit(:project_id, :name)
  end
  
  def record_params
    params.require(:record).permit(:duration_of_work, :record_date) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-inverse bg-inverse">
      <h2><%= link_to 'TimeTracker 2018', root_path, class: "navlink light-text" %></h2>
      <div class="row">
        <% if user_signed_in? %>
          <h3 class="col light-text"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></h3>
        <% else %>
          <div class="col">
            <h3 class="light-text"><%= link_to 'Sign Up!', new_user_registration_path %></h3>
          </div>
        <% end %>
        
      </div>
    </nav>
    
    
    
      <%= yield %>
    
  </body>
</html>

app/views/projects/edit.html.erb
<%= simple_form_for @project do |f| %>
  <div class="authentication-form">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.submit 'Update', class: 'btn btn-default', id: 'edit-project-submit' %>
  </div>
<% end %>

<h5 class="right dark-font"><%= link_to 'Return to Projects', root_path %></h5>

app/views/projects/index.html.erb
<button type="button" class="btn btn-default" id="new-project" data-toggle="modal" data-target="#NewProjectModal">New Project</button>

<div>
 
  <!-- Modal -->
  <div class="modal fade" id="NewProjectModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="NewProjectModalLabel">Add a New Project</h5>
        </div>
        <%= simple_form_for @project do |f| %>
          <div class="modal-body">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.submit 'Create', class: 'btn btn-default', id: 'new-project-submit' %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <br />
  <br />
  <% @projects.each do |project| %>
    <div class="row project">
      <h1 class="col-3"><%= project.name %></h1>
      <h3 class="col-3"><%= project.description %></h3>
      <div class="btn-group-lg">
        <a><%= link_to 'Add Record', new_project_record_path(project), class: "links" %></a>
        <a><%= link_to 'Summary', project_path(project), class: "links" %></a>
        <a><%= link_to 'Edit Project', edit_project_path(project), class: "links" %></a>
      </div>
    </div>
    <hr>
  <% end %>
  
</div>
 

app/views/projects/show.html.erb
<div class="center">
  <h1><%= @project.name %></h1>
  <h3><%= @project.description %></h3>
  <hr>
  <h2><%= @summary %> total hours worked</h2>
</div>

<h5 class="right  dark-font"><%= link_to 'Return to Projects', root_path %></h5>

app/views/records/new.html.erb
<div class="authentication-form">
  <h2><%= @project.name %></h2>
  <%= simple_form_for @record, url: project_records_path(@project) do |f| %>
    <%= f.input :duration_of_work %>
    <%= f.input :record_date %>
    <%= f.submit "Add Record" %>
  <% end %>
</div>

<h5 class="right"><%= link_to 'Return to Projects', root_path %></h5>